import { CommunityTemplate, CommunityType } from "./types";

export const COMMUNITY_TEMPLATES: Record<CommunityType, CommunityTemplate> = {
  SPORTS: {
    type: "SPORTS",
    name: "Sports Team / Athletic Club",
    emoji: "⚽",
    icon: "Trophy",
    tagline: "Fixtures, squad availability, match tactics & training",
    description: "Designed for football, cricket, basketball, running clubs, and athletic teams.",
    accentColor: "from-emerald-600 to-teal-700",
    coverPreset: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "EVENTS", "SPORTS_FIXTURES", "POLLS", "FILES", "CALLS"],
    defaultChannels: [
      { name: "general", description: "Team chatter and locker room discussion" },
      { name: "training", description: "Drills, practice schedules, and workout notes" },
      { name: "matches", description: "Upcoming fixtures, lineups, and match coordination" },
      { name: "announcements", description: "Coach and captain notices", type: "PUBLIC" },
      { name: "tactics-room", description: "Restricted strategy room for leadership", type: "ROLE_RESTRICTED" },
    ],
    defaultRoles: [
      {
        name: "Owner / President",
        systemType: "OWNER",
        priority: 100,
        color: "#f59e0b",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Coach",
        systemType: "ADMIN",
        priority: 80,
        color: "#3b82f6",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
        },
      },
      {
        name: "Captain",
        systemType: "MODERATOR",
        priority: 60,
        color: "#10b981",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
          CREATE_ANNOUNCEMENTS: true,
        },
      },
      {
        name: "Player",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  ORGANIZATION: {
    type: "ORGANIZATION",
    name: "Corporate Team / Startup",
    emoji: "🏢",
    icon: "Building2",
    tagline: "Cross-functional teams, projects, meetings & secure files",
    description: "Built for companies, startups, agencies, and agile departmental collaboration.",
    accentColor: "from-blue-700 to-indigo-800",
    coverPreset: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "EVENTS", "PROJECTS", "POLLS", "FILES", "CALLS"],
    defaultChannels: [
      { name: "general", description: "Company-wide updates and casual watercooler" },
      { name: "product-engineering", description: "Sprint goals, architecture & tech syncs" },
      { name: "marketing-growth", description: "Campaigns, analytics & design assets" },
      { name: "announcements", description: "Official corporate board notices" },
      { name: "leadership-sync", description: "Executive planning & strategy", type: "ROLE_RESTRICTED" },
    ],
    defaultRoles: [
      {
        name: "Founder / Executive",
        systemType: "OWNER",
        priority: 100,
        color: "#8b5cf6",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Team Lead",
        systemType: "ADMIN",
        priority: 70,
        color: "#2563eb",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
          CREATE_ANNOUNCEMENTS: true,
        },
      },
      {
        name: "Member",
        systemType: "MEMBER",
        priority: 20,
        color: "#475569",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  EDUCATION: {
    type: "EDUCATION",
    name: "Education / Campus / Course",
    emoji: "🎓",
    icon: "GraduationCap",
    tagline: "Academic notices, lecture schedules, classes & discussions",
    description: "For universities, research labs, high schools, coaching cohorts, and study circles.",
    accentColor: "from-indigo-600 to-violet-700",
    coverPreset: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "EVENTS", "FILES", "POLLS", "CALLS"],
    defaultChannels: [
      { name: "general", description: "Campus lounge and open discussion" },
      { name: "notices", description: "Official syllabus & exam deadlines" },
      { name: "study-materials", description: "Lecture notes, research papers, and slide decks" },
      { name: "faculty-room", description: "Private coordination for instructors", type: "ROLE_RESTRICTED" },
    ],
    defaultRoles: [
      {
        name: "Dean / Principal",
        systemType: "OWNER",
        priority: 100,
        color: "#d97706",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Teacher / Professor",
        systemType: "ADMIN",
        priority: 80,
        color: "#059669",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
          CREATE_ANNOUNCEMENTS: true,
        },
      },
      {
        name: "Student",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  GAMING: {
    type: "GAMING",
    name: "Gaming Guild / Clan / Esports",
    emoji: "🎮",
    icon: "Gamepad2",
    tagline: "Scrim schedules, voice channels, tournament clips & clan chat",
    description: "Tailored for competitive gaming rosters, Discord-style clans, and streamer communities.",
    accentColor: "from-purple-700 to-pink-600",
    coverPreset: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "EVENTS", "CALLS", "FILES", "POLLS"],
    defaultChannels: [
      { name: "lounge", description: "Casual memes and gameplay banter" },
      { name: "scrim-schedule", description: "Practice matches and squad lineups" },
      { name: "clips-and-highlights", description: "Ace plays and clutch clips" },
      { name: "officers", description: "Clan leaders and tournament staff", type: "ROLE_RESTRICTED" },
    ],
    defaultRoles: [
      {
        name: "Guild Master",
        systemType: "OWNER",
        priority: 100,
        color: "#a855f7",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Officer",
        systemType: "MODERATOR",
        priority: 70,
        color: "#ec4899",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
        },
      },
      {
        name: "Roster Member",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  CLUB: {
    type: "CLUB",
    name: "Club / Cultural / Music Band",
    emoji: "🎵",
    icon: "Music",
    tagline: "Jam sessions, exhibition planning, meetups & collective media",
    description: "For music bands, photography societies, theater troupes, and hobbyist groups.",
    accentColor: "from-rose-600 to-orange-600",
    coverPreset: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "EVENTS", "FILES", "POLLS", "CALLS"],
    defaultChannels: [
      { name: "general", description: "Club discussions and creative ideas" },
      { name: "events-calendar", description: "Upcoming rehearsals, gigs, and meetups" },
      { name: "shared-creatives", description: "Recordings, raw photos, and portfolios" },
      { name: "announcements", description: "Important club notices" },
    ],
    defaultRoles: [
      {
        name: "Club Leader",
        systemType: "OWNER",
        priority: 100,
        color: "#e11d48",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Organizer",
        systemType: "ADMIN",
        priority: 70,
        color: "#f97316",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
          CREATE_ANNOUNCEMENTS: true,
        },
      },
      {
        name: "Member",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  NGO: {
    type: "NGO",
    name: "NGO / Volunteer Organization",
    emoji: "🤝",
    icon: "HeartHandshake",
    tagline: "Relief drives, field volunteer schedules & mission updates",
    description: "For non-profits, volunteer groups, citizen initiatives, and charity missions.",
    accentColor: "from-teal-600 to-cyan-700",
    coverPreset: "https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "EVENTS", "POLLS", "FILES", "CALLS"],
    defaultChannels: [
      { name: "general", description: "Volunteer coordination and introductions" },
      { name: "field-updates", description: "Real-time updates from ongoing ground drives" },
      { name: "announcements", description: "Urgent mobilization notices & safety protocols" },
      { name: "resources", description: "Checklists, donor reports, and supply logs" },
    ],
    defaultRoles: [
      {
        name: "Director / Founder",
        systemType: "OWNER",
        priority: 100,
        color: "#0d9488",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Field Lead",
        systemType: "ADMIN",
        priority: 70,
        color: "#0891b2",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
          CREATE_ANNOUNCEMENTS: true,
        },
      },
      {
        name: "Volunteer",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  EVENT: {
    type: "EVENT",
    name: "Event / Wedding / Tournament",
    emoji: "📅",
    icon: "CalendarDays",
    tagline: "Schedule countdown, attendee RSVPs & ephemeral media gallery",
    description: "Built for weddings, reunions, hackathons, conferences, and time-bounded events.",
    accentColor: "from-amber-600 to-rose-600",
    coverPreset: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "EVENTS", "POLLS", "FILES", "CALLS"],
    defaultChannels: [
      { name: "general", description: "Guest welcome and general banter" },
      { name: "itinerary", description: "Official agenda, timings, and transportation" },
      { name: "photo-stream", description: "Live photos and video memories from the event" },
      { name: "announcements", description: "Organizer bulletins & live announcements" },
    ],
    defaultRoles: [
      {
        name: "Event Host",
        systemType: "OWNER",
        priority: 100,
        color: "#d97706",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Coordinator",
        systemType: "ADMIN",
        priority: 70,
        color: "#f43f5e",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
          CREATE_ANNOUNCEMENTS: true,
        },
      },
      {
        name: "Guest",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: false,
          CREATE_POLLS: false,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  FRIENDS: {
    type: "FRIENDS",
    name: "Friends Circle / Family Group",
    emoji: "👥",
    icon: "Users",
    tagline: "Group calls, plan polls, trip planning & shared media",
    description: "Ideal for close friend circles, vacation groups, and private family chats.",
    accentColor: "from-sky-600 to-blue-700",
    coverPreset: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "EVENTS", "POLLS", "FILES", "CALLS"],
    defaultChannels: [
      { name: "general", description: "Daily banter and memes" },
      { name: "weekend-plans", description: "Outing coordination and dinner polls" },
      { name: "media-vault", description: "Trips, memories, and photos" },
    ],
    defaultRoles: [
      {
        name: "Creator",
        systemType: "OWNER",
        priority: 100,
        color: "#0284c7",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Friend",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          CREATE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  PRIVATE: {
    type: "PRIVATE",
    name: "Private Group / Stealth Initiative",
    emoji: "🔒",
    icon: "Lock",
    tagline: "Zero discovery, invite-only, encrypted stealth communication",
    description: "For confidential advisory boards, stealth projects, and high-security groups.",
    accentColor: "from-slate-900 to-slate-950",
    coverPreset: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "FILES", "CALLS"],
    defaultChannels: [
      { name: "classified", description: "End-to-end encrypted direct channel" },
      { name: "announcements", description: "Broadcast briefs from leadership", type: "PUBLIC" },
    ],
    defaultRoles: [
      {
        name: "Owner",
        systemType: "OWNER",
        priority: 100,
        color: "#334155",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Member",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: false,
          CREATE_POLLS: false,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },

  CUSTOM: {
    type: "CUSTOM",
    name: "Custom Space",
    emoji: "✨",
    icon: "Sparkles",
    tagline: "Blank slate — configure your own roles, channels & modules",
    description: "Start from scratch and choose your exact modules, permissions, and layout.",
    accentColor: "from-indigo-900 via-slate-900 to-violet-950",
    coverPreset: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=1200&q=80",
    recommendedModules: ["CHANNELS", "ANNOUNCEMENTS", "EVENTS", "POLLS", "FILES", "CALLS"],
    defaultChannels: [
      { name: "general", description: "General community conversation" },
    ],
    defaultRoles: [
      {
        name: "Owner",
        systemType: "OWNER",
        priority: 100,
        color: "#4f46e5",
        permissions: {
          SEND_MESSAGES: true,
          DELETE_MESSAGES: true,
          ADD_MEMBERS: true,
          REMOVE_MEMBERS: true,
          INVITE_MEMBERS: true,
          CREATE_CHANNELS: true,
          MANAGE_COMMUNITY: true,
          CREATE_EVENTS: true,
          MANAGE_EVENTS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          DELETE_FILES: true,
          START_CALLS: true,
          ASSIGN_ROLES: true,
          CREATE_ANNOUNCEMENTS: true,
          MODERATE_CONTENT: true,
          MANAGE_MODULES: true,
        },
      },
      {
        name: "Member",
        systemType: "MEMBER",
        priority: 20,
        color: "#64748b",
        permissions: {
          SEND_MESSAGES: true,
          INVITE_MEMBERS: true,
          CREATE_POLLS: true,
          UPLOAD_FILES: true,
          START_CALLS: true,
        },
      },
    ],
  },
};
